# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Prathyk's Notes
tagline:          'IMHO'
description:      'Read at your own risk'
url:              https://prathyk.github.io/
baseurl:          /

author:
  name:           'Pratik T'
  url:            https://prathyk.github.io/

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/prathyk/
